apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-hpe
provisioner: hpe.com/cv
parameters:
  description: "Volume created by the HPE Volume Driver for Kubernetes FlexVolume Plugin"
  perfPolicy: "SQL Server"
  limitIOPS: "76800"
